### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imSunnyk** [vaibhav1929/pydrive-project#1]
I have xampp server for mysql, I started xampp and then both apache and mysql 
then opened phpmyadmin, I created database pydrive_db and imported the database..

"Installed django 3 and pymysql and then in pymysl folder I replaced given __init__.py file....

then I run commands 
python manage.py makemigrations 
but there errors coming 
first it came 

operation error : can't connect to sql server

now its new django.db.utils.InternalError: (1932, "Table 'pydrive_db.django_migrations' doesn't exist in engine")

if there is any other requirement to be installed or any thing please suggest and also...
please add some more detail, it would be helpful..
thank you...

**Comment by vaibhav1929** [comment]
Can you please share a screenshot of error along with project structure.
And if possible also share files located under *migrations* folder.

**Comment by imSunnyk** [comment]
this issue is coming for makemigraions, migrate and also for runserver

python3 manage.py makemigrations


Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.init_connection_state()
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 231, in init_connection_state
    if self.features.is_sql_auto_is_null_enabled:
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 82, in is_sql_auto_is_null_enabled
    cursor.execute('SELECT @@SQL_AUTO_IS_NULL')
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/home/sandeep/.local/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 146, in last_executed_query
    query = query.decode(errors='replace')
AttributeError: 'str' object has no attribute 'decode'
